In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from pandas import DataFrame

In [2]:
data = pd.read_csv('D:/Documents/Go Abroad/实习/成交金额/Python数据/2017.csv',encoding='gbk',engine='python')
data = data.set_index('date')
data = data[['stock','close','turnover_sum']]

In [5]:
L = []
for i in set(data["stock"]):
    b = list(data["stock"].values).count(i)
    L.append(b)

In [6]:
a = list(set(data["stock"]))
stock_m = a[L.index(max(L))]
stock_m

1

In [3]:
stock_m = 1

In [4]:
stock_eg = data[data['stock'] == stock_m]
stock_eg

            stock  close  turnover_sum
date
2017-01-03      1   9.16  4.205952e+08
2017-01-04      1   9.16  8.320986e+08
2017-01-05      1   9.17  1.147868e+09
2017-01-06      1   9.13  1.475045e+09
2017-01-09      1   9.15  1.805039e+09
2017-01-10      1   9.15  2.025614e+09
2017-01-11      1   9.14  2.303168e+09
2017-01-12      1   9.15  2.695037e+09
2017-01-13      1   9.16  3.092639e+09
2017-01-16      1   9.14  3.715665e+09
2017-01-17      1   9.15  4.213845e+09
2017-01-18      1   9.17  4.740271e+09
2017-01-19      1   9.18  5.142717e+09
2017-01-20      1   9.22  5.504582e+09
2017-01-23      1   9.22  5.892601e+09
2017-01-24      1   9.27  6.327389e+09
2017-01-25      1   9.26  6.609365e+09
2017-01-26      1   9.33  7.001209e+09
2017-02-03      1   9.26  7.293827e+09
2017-02-06      1   9.31  7.774269e+09
2017-02-07      1   9.30  8.143024e+09
2017-02-08      1   9.30  8.476999e+09
2017-02-09      1   9.31  8.796200e+09
2017-02-10      1   9.33  9.246902e+09
2017-02-13      1   9.41  9.846853e+09
2017-02-14      1   9.40  1.018717e+10
2017-02-15      1   9.45  1.090393e+10
2017-02-16      1   9.46  1.129257e+10
2017-02-17      1   9.39  1.169273e+10
2017-02-20      1   9.56  1.254844e+10
...           ...    ...           ...
2017-11-20      1  14.25  1.890038e+11
2017-11-21      1  14.45  1.926137e+11
2017-11-22      1  15.10  1.964532e+11
2017-11-23      1  14.35  2.000160e+11
2017-11-24      1  14.56  2.037486e+11
2017-11-27      1  13.93  2.066271e+11
2017-11-28      1  13.70  2.090236e+11
2017-11-29      1  13.82  2.111720e+11
2017-11-30      1  13.38  2.130387e+11
2017-12-01      1  13.00  2.153930e+11
2017-12-04      1  13.30  2.173163e+11
2017-12-05      1  13.30  2.196181e+11
2017-12-06      1  13.08  2.217223e+11
2017-12-07      1  12.83  2.232493e+11
2017-12-08      1  13.09  2.250007e+11
2017-12-11      1  13.50  2.279814e+11
2017-12-12      1  13.02  2.302838e+11
2017-12-13      1  13.13  2.319628e+11
2017-12-14      1  13.00  2.332739e+11
2017-12-15      1  12.72  2.346793e+11
2017-12-18      1  12.75  2.357087e+11
2017-12-19      1  13.28  2.388474e+11
2017-12-20      1  13.26  2.403112e+11
2017-12-21      1  13.54  2.423168e+11
2017-12-22      1  13.52  2.433214e+11
2017-12-25      1  13.25  2.454664e+11
2017-12-26      1  13.66  2.469772e+11
2017-12-27      1  13.29  2.488254e+11
2017-12-28      1  13.21  2.508783e+11
2017-12-29      1  13.30  2.521816e+11

[244 rows x 3 columns]

In [11]:
suoyin = list(stock_eg.index)
stock_sum = data[data["stock"] == list(set(data["stock"]))[0]]
stock_sum = stock_sum.reindex(suoyin,method='ffill')
close = stock_sum['close']
change = close.pct_change(periods=1, fill_method='pad')
stock_sum["change"] = change
stock_sum

            stock  close  turnover_sum    change
date
2017-01-03      1   9.16  4.205952e+08       NaN
2017-01-04      1   9.16  8.320986e+08  0.000000
2017-01-05      1   9.17  1.147868e+09  0.001092
2017-01-06      1   9.13  1.475045e+09 -0.004362
2017-01-09      1   9.15  1.805039e+09  0.002191
2017-01-10      1   9.15  2.025614e+09  0.000000
2017-01-11      1   9.14  2.303168e+09 -0.001093
2017-01-12      1   9.15  2.695037e+09  0.001094
2017-01-13      1   9.16  3.092639e+09  0.001093
2017-01-16      1   9.14  3.715665e+09 -0.002183
2017-01-17      1   9.15  4.213845e+09  0.001094
2017-01-18      1   9.17  4.740271e+09  0.002186
2017-01-19      1   9.18  5.142717e+09  0.001091
2017-01-20      1   9.22  5.504582e+09  0.004357
2017-01-23      1   9.22  5.892601e+09  0.000000
2017-01-24      1   9.27  6.327389e+09  0.005423
2017-01-25      1   9.26  6.609365e+09 -0.001079
2017-01-26      1   9.33  7.001209e+09  0.007559
2017-02-03      1   9.26  7.293827e+09 -0.007503
2017-02-06      1   9.31  7.774269e+09  0.005400
2017-02-07      1   9.30  8.143024e+09 -0.001074
2017-02-08      1   9.30  8.476999e+09  0.000000
2017-02-09      1   9.31  8.796200e+09  0.001075
2017-02-10      1   9.33  9.246902e+09  0.002148
2017-02-13      1   9.41  9.846853e+09  0.008574
2017-02-14      1   9.40  1.018717e+10 -0.001063
2017-02-15      1   9.45  1.090393e+10  0.005319
2017-02-16      1   9.46  1.129257e+10  0.001058
2017-02-17      1   9.39  1.169273e+10 -0.007400
2017-02-20      1   9.56  1.254844e+10  0.018104
...           ...    ...           ...       ...
2017-11-20      1  14.25  1.890038e+11  0.081184
2017-11-21      1  14.45  1.926137e+11  0.014035
2017-11-22      1  15.10  1.964532e+11  0.044983
2017-11-23      1  14.35  2.000160e+11 -0.049669
2017-11-24      1  14.56  2.037486e+11  0.014634
2017-11-27      1  13.93  2.066271e+11 -0.043269
2017-11-28      1  13.70  2.090236e+11 -0.016511
2017-11-29      1  13.82  2.111720e+11  0.008759
2017-11-30      1  13.38  2.130387e+11 -0.031838
2017-12-01      1  13.00  2.153930e+11 -0.028401
2017-12-04      1  13.30  2.173163e+11  0.023077
2017-12-05      1  13.30  2.196181e+11  0.000000
2017-12-06      1  13.08  2.217223e+11 -0.016541
2017-12-07      1  12.83  2.232493e+11 -0.019113
2017-12-08      1  13.09  2.250007e+11  0.020265
2017-12-11      1  13.50  2.279814e+11  0.031322
2017-12-12      1  13.02  2.302838e+11 -0.035556
2017-12-13      1  13.13  2.319628e+11  0.008449
2017-12-14      1  13.00  2.332739e+11 -0.009901
2017-12-15      1  12.72  2.346793e+11 -0.021538
2017-12-18      1  12.75  2.357087e+11  0.002358
2017-12-19      1  13.28  2.388474e+11  0.041569
2017-12-20      1  13.26  2.403112e+11 -0.001506
2017-12-21      1  13.54  2.423168e+11  0.021116
2017-12-22      1  13.52  2.433214e+11 -0.001477
2017-12-25      1  13.25  2.454664e+11 -0.019970
2017-12-26      1  13.66  2.469772e+11  0.030943
2017-12-27      1  13.29  2.488254e+11 -0.027086
2017-12-28      1  13.21  2.508783e+11 -0.006020
2017-12-29      1  13.30  2.521816e+11  0.006813

[244 rows x 4 columns]

In [12]:
for i in list(set(data["stock"])):
    stock_q = data[data["stock"] == i]
    stock_qb = stock_q.reindex(suoyin,method='ffill')
    close = stock_qb['close']
    change = close.pct_change(periods=1, fill_method='pad')
    stock_qb["change"] = change
    stock_sum = stock_sum.append(stock_qb)
stock_sum

               stock  close  turnover_sum    change
date
2017-01-03       1.0   9.16  4.205952e+08       NaN
2017-01-04       1.0   9.16  8.320986e+08  0.000000
2017-01-05       1.0   9.17  1.147868e+09  0.001092
2017-01-06       1.0   9.13  1.475045e+09 -0.004362
2017-01-09       1.0   9.15  1.805039e+09  0.002191
2017-01-10       1.0   9.15  2.025614e+09  0.000000
2017-01-11       1.0   9.14  2.303168e+09 -0.001093
2017-01-12       1.0   9.15  2.695037e+09  0.001094
2017-01-13       1.0   9.16  3.092639e+09  0.001093
2017-01-16       1.0   9.14  3.715665e+09 -0.002183
2017-01-17       1.0   9.15  4.213845e+09  0.001094
2017-01-18       1.0   9.17  4.740271e+09  0.002186
2017-01-19       1.0   9.18  5.142717e+09  0.001091
2017-01-20       1.0   9.22  5.504582e+09  0.004357
2017-01-23       1.0   9.22  5.892601e+09  0.000000
2017-01-24       1.0   9.27  6.327389e+09  0.005423
2017-01-25       1.0   9.26  6.609365e+09 -0.001079
2017-01-26       1.0   9.33  7.001209e+09  0.007559
2017-02-03       1.0   9.26  7.293827e+09 -0.007503
2017-02-06       1.0   9.31  7.774269e+09  0.005400
2017-02-07       1.0   9.30  8.143024e+09 -0.001074
2017-02-08       1.0   9.30  8.476999e+09  0.000000
2017-02-09       1.0   9.31  8.796200e+09  0.001075
2017-02-10       1.0   9.33  9.246902e+09  0.002148
2017-02-13       1.0   9.41  9.846853e+09  0.008574
2017-02-14       1.0   9.40  1.018717e+10 -0.001063
2017-02-15       1.0   9.45  1.090393e+10  0.005319
2017-02-16       1.0   9.46  1.129257e+10  0.001058
2017-02-17       1.0   9.39  1.169273e+10 -0.007400
2017-02-20       1.0   9.56  1.254844e+10  0.018104
...              ...    ...           ...       ...
2017-11-20  600814.0   8.59  2.611421e+10 -0.004635
2017-11-21  600814.0   8.59  2.613794e+10  0.000000
2017-11-22  600814.0   8.70  2.616090e+10  0.012806
2017-11-23  600814.0   8.47  2.618071e+10 -0.026437
2017-11-24  600814.0   9.32  2.624242e+10  0.100354
2017-11-27  600814.0   9.18  2.637654e+10 -0.015021
2017-11-28  600814.0   9.19  2.644768e+10  0.001089
2017-11-29  600814.0   9.10  2.650272e+10 -0.009793
2017-11-30  600814.0   9.07  2.655832e+10 -0.003297
2017-12-01  600814.0   9.07  2.660100e+10  0.000000
2017-12-04  600814.0   9.02  2.663289e+10 -0.005513
2017-12-05  600814.0   8.63  2.668977e+10 -0.043237
2017-12-06  600814.0   8.75  2.671787e+10  0.013905
2017-12-07  600814.0   8.68  2.673691e+10 -0.008000
2017-12-08  600814.0   8.99  2.680755e+10  0.035714
2017-12-11  600814.0   9.43  2.692529e+10  0.048943
2017-12-12  600814.0   9.12  2.698947e+10 -0.032874
2017-12-13  600814.0   9.23  2.703060e+10  0.012061
2017-12-14  600814.0   9.42  2.712786e+10  0.020585
2017-12-15  600814.0   9.51  2.726566e+10  0.009554
2017-12-18  600814.0   9.17  2.735379e+10 -0.035752
2017-12-19  600814.0   9.18  2.740286e+10  0.001091
2017-12-20  600814.0   9.18  2.745271e+10  0.000000
2017-12-21  600814.0   8.91  2.750864e+10 -0.029412
2017-12-22  600814.0   8.92  2.753514e+10  0.001122
2017-12-25  600814.0   8.80  2.756422e+10 -0.013453
2017-12-26  600814.0   8.91  2.758896e+10  0.012500
2017-12-27  600814.0   8.86  2.760898e+10 -0.005612
2017-12-28  600814.0   8.86  2.763716e+10  0.000000
2017-12-29  600814.0   9.00  2.766045e+10  0.015801

[824964 rows x 4 columns]

In [13]:
len(set(data["stock"]))

3380

In [14]:
a[L.index(min(L))]

600890

In [18]:
stock_sum[stock_sum["stock"] == 600890]

               stock  close  turnover_sum  change
date
2017-12-29  600890.0  10.21   352064194.0     NaN

In [ ]:
stock.replace(np.nan,0)