In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from pandas import DataFrame

In [2]:
data = pd.read_table('D:/Documents/Go Abroad/实习/成交金额/原始数据/2017.txt',encoding='gbk',engine='python')

In [3]:
data = data.set_index('Trddt')
data.columns = ["stock","close","volume","turnover","value"]
data.index.name = "date"

In [4]:
#data.columns = ["stock", "date", "close","volume","turnover","value"]

In [5]:
data

             stock  close     volume      turnover         value
date
2017-12-29       1  13.30   98291553  1.303222e+09  2.250093e+08
2017-12-28       1  13.21  155303047  2.052945e+09  2.234866e+08
2017-12-27       1  13.29  136656673  1.848165e+09  2.248401e+08
2017-12-26       1  13.66  112368845  1.510826e+09  2.310997e+08
2017-12-25       1  13.25  158556718  2.145041e+09  2.241634e+08
2017-12-22       1  13.52   74290095  1.004526e+09  2.287312e+08
2017-12-21       1  13.54  148520344  2.005618e+09  2.290696e+08
2017-12-20       1  13.26  110624507  1.463802e+09  2.243325e+08
2017-12-19       1  13.28  239794295  3.138688e+09  2.246709e+08
2017-12-18       1  12.75   80546452  1.029423e+09  2.157044e+08
2017-12-15       1  12.72  109995250  1.405372e+09  2.151968e+08
2017-12-14       1  13.00  100199798  1.311132e+09  2.199339e+08
2017-12-13       1  13.13  128924811  1.679022e+09  2.221332e+08
2017-12-12       1  13.02  174340579  2.302355e+09  2.202722e+08
2017-12-11       1  13.50  226195273  2.980736e+09  2.283929e+08
2017-12-08       1  13.09  135131504  1.751423e+09  2.214565e+08
2017-12-07       1  12.83  118195784  1.526953e+09  2.170578e+08
2017-12-06       1  13.08  161984496  2.104169e+09  2.212873e+08
2017-12-05       1  13.30  172368132  2.301868e+09  2.250093e+08
2017-12-04       1  13.30  145402345  1.923316e+09  2.250093e+08
2017-12-01       1  13.00  178493315  2.354300e+09  2.199339e+08
2017-11-30       1  13.38  137963571  1.866701e+09  2.263627e+08
2017-11-29       1  13.82  156409493  2.148313e+09  2.338066e+08
2017-11-28       1  13.70  176643250  2.396540e+09  2.317765e+08
2017-11-27       1  13.93  206408533  2.878492e+09  2.356676e+08
2017-11-24       1  14.56  263018967  3.732597e+09  2.463259e+08
2017-11-23       1  14.35  242914214  3.562843e+09  2.427732e+08
2017-11-22       1  15.10  257023146  3.839501e+09  2.554616e+08
2017-11-21       1  14.45  249532781  3.609849e+09  2.444650e+08
2017-11-20       1  14.25  284392582  3.860145e+09  2.410814e+08
...            ...    ...        ...           ...           ...
2017-02-20  603999  28.43    2556009  7.238744e+07  3.275136e+06
2017-02-17  603999  28.24    3793120  1.079906e+08  3.253248e+06
2017-02-16  603999  28.53    3168219  9.009535e+07  3.286656e+06
2017-02-15  603999  28.70    6670337  1.922295e+08  3.306240e+06
2017-02-14  603999  28.47    2508570  7.142309e+07  3.279744e+06
2017-02-13  603999  28.64    3444123  9.844175e+07  3.299328e+06
2017-02-10  603999  28.31    3641180  1.034810e+08  3.261312e+06
2017-02-09  603999  28.79    4701220  1.349776e+08  3.316608e+06
2017-02-08  603999  28.50    3733147  1.052044e+08  3.283200e+06
2017-02-07  603999  28.32    4965434  1.409954e+08  3.262464e+06
2017-02-06  603999  28.06    2801888  7.782757e+07  3.232512e+06
2017-02-03  603999  27.49    1429620  3.936636e+07  3.166848e+06
2017-01-26  603999  27.53    1803960  4.961134e+07  3.171456e+06
2017-01-25  603999  27.45    1842642  5.060575e+07  3.162240e+06
2017-01-24  603999  27.45    3136060  8.642267e+07  3.162240e+06
2017-01-23  603999  28.11    4210592  1.181965e+08  3.238272e+06
2017-01-20  603999  27.75    3078421  8.510478e+07  3.196800e+06
2017-01-19  603999  27.35    2859736  7.817610e+07  3.150720e+06
2017-01-18  603999  27.22    2493120  6.789564e+07  3.135744e+06
2017-01-17  603999  27.40    4039158  1.089060e+08  3.156480e+06
2017-01-16  603999  26.88    6242124  1.708683e+08  3.096576e+06
2017-01-13  603999  29.28    4020980  1.186741e+08  3.373056e+06
2017-01-12  603999  30.02    3287621  9.880962e+07  3.458304e+06
2017-01-11  603999  29.97    5047620  1.525571e+08  3.452544e+06
2017-01-10  603999  30.93    6044817  1.870556e+08  3.563136e+06
2017-01-09  603999  31.46    9801473  3.071947e+08  3.624192e+06
2017-01-06  603999  30.41    4202944  1.272411e+08  3.503232e+06
2017-01-05  603999  30.15    3930629  1.188813e+08  3.473280e+06
2017-01-04  603999  30.52    5290800  1.602896e+08  3.515904e+06
2017-01-03  603999  30.05    3414944  1.015842e+08  3.461760e+06

[740507 rows x 5 columns]

In [7]:
def sort():
    sort_index()


data.groupby(data['stock']).transform(sort)

TypeError: Transform function invalid for data types

In [3]:
data = data.set_index('Trddt')
data.columns = ["stock","close","volume","turnover","value"]
data.index.name = "date"

·尝试groupby方法

In [5]:
data.groupby(data['stock']).

AttributeError: Cannot access callable attribute 'sort_index' of 'DataFrameGroupBy' objects, try using the 'apply' method

·循环方法

In [3]:
def data_processing(data):
    
    ######将读取的原始数据进行简单处理，以日期作为索引，并将"stock","close","volume","turnover","value"作为列名#########
    data = data.set_index('Trddt')
    data.columns = ["stock","close","volume","turnover","value"]
    data.index.name = "date"

    stock_sum = pd.DataFrame(columns = ['stock', 'close', 'volume', 'turnover', 'value', 'turnover_sum', 'change'])  ##建立一个空的dataframe

    ######对所有股票进行循环，并将其存入stock_sum中#######################
    for i in list(set(data["stock"]))[0:2]:
        stock_eg = data[data["stock"] == i]
        stock_eg = stock_eg.sort_index()                  #将dataframe按照索引从小到大排列
        turnover = stock_eg['turnover']
        close = stock_eg["close"]
        turnover_sum = sum_accum(turnover,len(stock_eg))
        change = close.pct_change(periods=1, fill_method='pad')    #求每日涨跌函数
        stock_eg["turnover_sum"] = turnover_sum
        stock_eg["change"] = change
        stock_sum = stock_sum.append(stock_eg)
    return stock_sum

In [6]:
stock2017 = data_processing(data)
stock2017

,stock,close,volume,turnover,value,turnover_sum,change
2017-01-03,1,9.16,45984049,4.205952e+08,1.340216e+08,4.205952e+08,NaN
2017-01-04,1,9.16,44932953,4.115034e+08,1.340216e+08,8.320986e+08,0.000000
2017-01-05,1,9.17,34437291,3.157697e+08,1.341679e+08,1.147868e+09,0.001092
2017-01-06,1,9.13,35815420,3.271764e+08,1.335827e+08,1.475045e+09,-0.004362
2017-01-09,1,9.15,36108157,3.299946e+08,1.547996e+08,1.805039e+09,0.002191
2017-01-10,1,9.15,24105395,2.205751e+08,1.547996e+08,2.025614e+09,0.000000
2017-01-11,1,9.14,30343089,2.775532e+08,1.546304e+08,2.303168e+09,-0.001093
2017-01-12,1,9.15,42800677,3.918694e+08,1.547996e+08,2.695037e+09,0.001094
2017-01-13,1,9.16,43430137,3.976019e+08,1.549688e+08,3.092639e+09,0.001093
2017-01-16,1,9.14,68316586,6.230258e+08,1.546304e+08,3.715665e+09,-0.002183
2017-01-17,1,9.15,54555237,4.981797e+08,1.547996e+08,4.213845e+09,0.001094
2017-01-18,1,9.17,57426939,5.264266e+08,1.551380e+08,4.740271e+09,0.002186
2017-01-19,1,9.18,43771286,4.024456e+08,1.553071e+08,5.142717e+09,0.001091
2017-01-20,1,9.22,39332857,3.618652e+08,1.559839e+08,5.504582e+09,0.004357
2017-01-23,1,9.22,42029931,3.880191e+08,1.559839e+08,5.892601e+09,0.000000
2017-01-24,1,9.27,47024408,4.347877e+08,1.568298e+08,6.327389e+09,0.005423
2017-01-25,1,9.26,30440196,2.819763e+08,1.566606e+08,6.609365e+09,-0.001079
2017-01-26,1,9.33,42071258,3.918443e+08,1.578448e+08,7.001209e+09,0.007559
2017-02-03,1,9.26,31547224,2.926179e+08,1.566606e+08,7.293827e+09,-0.007503
2017-02-06,1,9.31,51678611,4.804413e+08,1.575065e+08,7.774269e+09,0.005400
2017-02-07,1,9.30,39688497,3.687553e+08,1.573373e+08,8.143024e+09,-0.001074
2017-02-08,1,9.30,36027242,3.339754e+08,1.573373e+08,8.476999e+09,0.000000
2017-02-09,1,9.31,34285513,3.192010e+08,1.575065e+08,8.796200e+09,0.001075
2017-02-10,1,9.33,48274323,4.507013e+08,1.578448e+08,9.246902e+09,0.002148
2017-02-13,1,9.41,63836475,5.999510e+08,1.591983e+08,9.846853e+09,0.008574
2017-02-14,1,9.40,36240460,3.403184e+08,1.590291e+08,1.018717e+10,-0.001063
2017-02-15,1,9.45,75661306,7.167597e+08,1.598750e+08,1.090393e+10,0.005319
2017-02-16,1,9.46,41116113,3.886362e+08,1.600442e+08,1.129257e+10,0.001058
2017-02-17,1,9.39,42377497,4.001618e+08,1.588599e+08,1.169273e+10,-0.007400
2017-02-20,1,9.56,89875539,8.557108e+08,1.617360e+08,1.254844e+10,0.018104
...,...,...,...,...,...,...,...
2017-11-20,2,28.90,39508849,1.118756e+09,2.805949e+08,2.074794e+11,0.000000
2017-11-21,2,31.79,108178862,3.289379e+09,3.086544e+08,2.107688e+11,0.100000
2017-11-22,2,32.50,105296977,3.398211e+09,3.155479e+08,2.141670e+11,0.022334
2017-11-23,2,31.30,58032538,1.851670e+09,3.038969e+08,2.160187e+11,-0.036923
2017-11-24,2,31.80,52434306,1.653488e+09,3.087515e+08,2.176721e+11,0.015974
2017-11-27,2,31.52,52158128,1.640697e+09,3.060329e+08,2.193128e+11,-0.008805
2017-11-28,2,30.75,40578649,1.243496e+09,2.985568e+08,2.205563e+11,-0.024429
2017-11-29,2,33.82,89771259,2.894401e+09,3.283640e+08,2.234507e+11,0.099837
2017-11-30,2,31.22,100066549,3.213854e+09,3.031201e+08,2.266646e+11,-0.076878
2017-12-01,2,30.73,55743855,1.733100e+09,2.983626e+08,2.283977e+11,-0.015695
2017-12-04,2,30.85,37989001,1.160069e+09,2.995277e+08,2.295578e+11,0.003905
2017-12-05,2,31.03,56430201,1.747241e+09,3.012754e+08,2.313050e+11,0.005835
2017-12-06,2,30.77,38979445,1.197518e+09,2.987510e+08,2.325025e+11,-0.008379
2017-12-07,2,29.95,59000716,1.807843e+09,2.907895e+08,2.343104e+11,-0.026649
2017-12-08,2,29.82,58818718,1.731419e+09,2.895273e+08,2.360418e+11,-0.004341
2017-12-11,2,29.93,50213546,1.487021e+09,2.905953e+08,2.375288e+11,0.003689
2017-12-12,2,29.57,46763892,1.401463e+09,2.871000e+08,2.389303e+11,-0.012028
2017-12-13,2,29.94,33495394,9.981535e+08,2.906924e+08,2.399284e+11,0.012513
2017-12-14,2,30.11,38206777,1.150698e+09,2.923430e+08,2.410791e+11,0.005678
2017-12-15,2,29.11,39622918,1.165712e+09,2.826338e+08,2.422448e+11,-0.033212
2017-12-18,2,28.46,42128694,1.207131e+09,2.763228e+08,2.434520e+11,-0.022329
2017-12-19,2,29.16,34008410,9.815406e+08,2.831193e+08,2.444335e+11,0.024596
2017-12-20,2,28.60,32902669,9.431873e+08,2.776821e+08,2.453767e+11,-0.019204
2017-12-21,2,29.72,59516386,1.756899e+09,2.885564e+08,2.471336e+11,0.039161
2017-12-22,2,29.85,34220642,1.023085e+09,2.898186e+08,2.481567e+11,0.004374
2017-12-25,2,30.37,50638257,1.561915e+09,2.948673e+08,2.497186e+11,0.017420
2017-12-26,2,30.50,27884561,8.503080e+08,2.961295e+08,2.505689e+11,0.004281
2017-12-27,2,30.79,39548884,1.218293e+09,2.989452e+08,2.517872e+11,0.009508
2017-12-28,2,30.70,36731618,1.117505e+09,2.980714e+08,2.529047e+11,-0.002923
2017-12-29,2,31.06,38530740,1.204646e+09,3.015667e+08,2.541093e+11,0.011726